### ISSUE TITLE
sessiontoken写入文件内部

### ISSUE THREAD

**Issue by yabostone** [W4J1e/picgo-plugin-dogecloud#1]
每次都要调用api获取sessionToken，为什么不直接写入插件中呢？

**Comment by W4J1e** [comment]
> 每次都要调用api获取sessionToken，为什么不直接写入插件中呢？

我此前也想到过如果能自动化获取和填充这些参数会方便很多。但这是一个非独立的脚本，功能基本是Picgo决定的，所以我有些无从下手。
如果大佬有好的思路和实践欢迎PR 。

**Comment by yabostone** [comment]
那我看看插件开发要求。

**Comment by yabostone** [comment]
现在这个插件能用吗？我测试的时候报header错误，
InvalidRequest: Missing required header for this request: Appid, Bucket format should be <bucketname>-<appid>。
写到快完成调试时候发现报错了。

**Comment by W4J1e** [comment]
> 

我有阵子没用了，得晚上回去测试一下才知道。

**Comment by W4J1e** [comment]
@yabostone 测试了一下，插件功能正常，上传正常。

**Comment by yabostone** [comment]
上传成功了，我接着改代码了。

**Comment by W4J1e** [comment]
#2

**Comment by W4J1e** [comment]
我刚刚测试了一下，在windows 2.3.0版本的picogo客户端中，安装插件后实际无法正确显示插件，不知道大佬那里是否正常。
我重新拉取一下代码再仔细看看。
感谢贡献。

**Comment by yabostone** [comment]
我只在picgo-core下测试过，，因为开发环境是dockerContainer，，

**Comment by yabostone** [comment]
报的什么错有提示么？

**Comment by W4J1e** [comment]
@yabostone 构建没报错，安装也没报错，并且会显示已安装，但是实际上图床设置里没有对应的插件，再次点击插件设置输入插件名会看到插件是未安装状态，即便重启了picgo。
事实上在`C:\Users\用户名\AppData\Roaming\picgo\node_modules\`里有对应的插件内容。我把代码拉下来本地构建之后离线导入也是一样，没有任何提示，在picgo日志里看到如下：
```
2022-03-31 23:04:38 [PicGo SUCCESS] 插件安装成功 
2022-03-31 23:04:41 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module 'aws-sdk'
Require stack:
- C:\Users\W4j1e\Desktop\p\dist\uploader.js
- C:\Users\W4j1e\Desktop\p\dist\index.js
- E:\Program Files\picgo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js
- E:\Program Files\picgo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js
- E:\Program Files\picgo\resources\app.asar\node_modules\picgo\dist\src\index.js
- E:\Program Files\picgo\resources\app.asar\background.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (E:\Program Files\picgo\resources\electron.asar\common\reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\W4j1e\Desktop\p\dist\uploader.js:6:35)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
-------Error Stack End------- 
2022-03-31 23:04:41 [PicGo INFO] [PicGo Server] is listening at 36677 
```

**Comment by yabostone** [comment]
package.json 内需要导入aws sdk的安装包。
这个是用来npm上传时确认依赖用的，本地是自己npm install 下载。

**Comment by yabostone** [comment]
aws-sdk@2.1104.0
改成aws-sdk@2.1104.0
我接触nodejs和ts才几天，还不会构建package.json..

**Comment by W4J1e** [comment]
@yabostone 太难了。目前面临的问题在于，此前通过github Action自动构建和发版本为3.0.0的包到npm成功，但是在线安装之后插件不会出现在pigco的界面里。
然后我自己本地构建的时候就卡在了npm install这一步……有可能是我的node版本问题。我再测试一下。
![1](https://user-images.githubusercontent.com/74824162/161091845-c8868518-f1ce-4852-819a-4fccb65e33b2.jpg)

**Comment by yabostone** [comment]
npm 升级到8.3.1试试。

**Comment by yabostone** [comment]
npm: '8.3.1',
node: '16.14.0',

**Comment by W4J1e** [comment]
@yabostone 好的，我再试试。

**Comment by yabostone** [comment]
我更新了之前没有上传的一些文件，你到我的fork页面下再构建试试。测试成功后再pr。。

**Comment by W4J1e** [comment]
@yabostone folk页面的提交也没有上传内容诶，我更新了npm版本之后构建没有报错了，但是本地导入到picgo并重启后仍然和此前一样。
![1](https://user-images.githubusercontent.com/74824162/161097271-d098544e-16d0-4d97-abf9-4b86d09f6182.jpg)

![2](https://user-images.githubusercontent.com/74824162/161097283-eae2db27-f04c-47be-8f93-4334c73ce0f8.jpg)

**Comment by yabostone** [comment]
![image](https://user-images.githubusercontent.com/9281463/161097675-3678ade5-2d18-43e6-a30d-2be35722449d.png)
![image](https://user-images.githubusercontent.com/9281463/161098242-8f0fe708-69d2-41ea-a131-8c90373704b8.png)
我本地上传的成功了。。。

**Comment by yabostone** [comment]
你试着卸载后，再重启再本地安装试试，我第一次用picgo装插件compressed装了3小时，就是没有完全退出，完全卸载后再装。

**Comment by W4J1e** [comment]
我已经用geek install完全卸载了pigco，然后重新安装，再导入本地插件，然后重启picgo，还是空白。
是不是folk的仓库里还有东西没推上来？我是直接clone的folk仓库然后本地构建的。

**Comment by yabostone** [comment]
我也是git pull 再本地安装的啊。。
![image](https://user-images.githubusercontent.com/9281463/161099607-0320d769-7ede-4e4c-a69b-d75f833d2e45.png)

**Comment by W4J1e** [comment]
npm太折磨了，我首先npm install之后再npm run build，没有报错。本地导入到picgo不显示。
然后运行了一下`npm audit fix --force`，再构建就报错了。
我重新拉取一下试试吧。
![3](https://user-images.githubusercontent.com/74824162/161100435-3fa5bfd0-8f46-462b-b54d-8c04bf49f14f.jpg)
![4](https://user-images.githubusercontent.com/74824162/161100460-4d7e247f-6571-4b50-b109-ea31765c3016.jpg)

**Comment by yabostone** [comment]
![image](https://user-images.githubusercontent.com/9281463/161100673-9ba3918b-c698-412c-88e7-24e8b3825ee0.png)
到任务管理器kill掉picgo试试。

**Comment by yabostone** [comment]
js下面各种分支，nodejs,typescript,coffeescript,browerjs,变来变去的，没见其他哪种语言这样。

**Comment by W4J1e** [comment]
我全部重新做了一遍，还是老样子，重启、杀掉进程。甚至修改了aws的版本号再来一遍也是如此，picgo日志里显示如图：
![1](https://user-images.githubusercontent.com/74824162/161103413-1e601a9b-7a90-4d81-a1c1-c16ded8734c4.jpg)
我明天再看看吧，还要早起上班来着-.-

**Comment by yabostone** [comment]
我也要睡了，晚安。

**Comment by yabostone** [comment]
我在不同环境下试了picgo-core和picgo-GUI，nodejs和npm其实都不一样，都可用。
```
npm: '8.5.0',
node: '16.14.2',
```

```
PS C:\Users\mx> npm config get registry
https://registry.npmmirror.com/
```

**Comment by W4J1e** [comment]
要不麻烦你抽空看一下其它的配置问题吧。我昨晚pr了之后由action指定node版本编译了一次，npm版本好像也是8.3.1（就是上面你说的那个版本），但是我在picgo安装3.0.1的时候提示加载插件出错，picgo日志里显示无法找到picgo啥啥啥的。猜测可能是模块没有正确被安装。

**Comment by yabostone** [comment]
我看看。

**Comment by W4J1e** [comment]
@yabostone 我发现问题了。此前本地构建和action构建的只会生成dist文件夹和里面的js、ts文件，也就是2.0.x版本都只有dist文件夹、Liences和package.json以及README文件，能正常使用。
3.0.x版本，我本地构建之后仍然只保留了这几个文件，而不是把整个包括`node_modules`导入进去，导致加载插件的时候提示找不到xx模块。
看样子得修改一下构建脚本。
但是上传报错如下：
```
2022-04-01 13:10:30 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open './token.json'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as openSync] (electron/js2c/asar.js:138:31)
    at Object.readFileSync (fs.js:349:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at Object.handle (D:\test\picgo-plugin-dogecloud\picgo-plugin-dogecloud\dist\index.js:105:20)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (E:\Program Files\picgo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (E:\Program Files\picgo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
-------Error Stack End------- 
```

**Comment by yabostone** [comment]
这个我知道了，要改代码，之前的token.json没有创建先写入。

**Comment by W4J1e** [comment]
辛苦大佬改一下，这方面我挺白痴的，万分感谢。

**Comment by W4J1e** [comment]
目前已经发版到npm，我这里测试一切正常。
感觉package挺迷的，我尝试过在本地多次修改，如果只安装`package.json`里面要求的依赖，会提示缺少一些依赖，估计是依赖的依赖没安装。如果直接`npm install`会下载几百个包，导致安装插件速度变慢。
目前下载要安装70来个包，相对来说好一些了。npm这玩意。。。
**最后，再次感谢大佬的辛苦付出！**

**Comment by yabostone** [comment]
每种语言都是这样，nodejs版本太多了。
查了资料 应该用
`npm install . --save-dev` 安装开发依赖包。
上传的时候只是Dependencies。

**Comment by yabostone** [comment]
还是报错，自己测的就能过。。。我再改改代码，，

**Comment by W4J1e** [comment]
以后试试用yarn管理依赖。
我刚才卸载重装了插件是正常的，我换台电脑再试试。

**Comment by yabostone** [comment]
需要refreshtoken开了上传一次，再关掉才可以用，异步编程我也不熟悉。。

**Comment by W4J1e** [comment]
我也发现了，在我台式上上传是正常的，但是在笔记本上新安装了测试，也是报 json 那个错，无论开不开强制刷新。就很迷。

**Comment by yabostone** [comment]
开后，上传文件，再关掉试试。

**Comment by W4J1e** [comment]
> 

也一样的，开了上传报失败，再关了上传也是一样的报错。

**Comment by yabostone** [comment]
不行，报错的厉害，明天再来调一下。

**Comment by W4J1e** [comment]
我昨晚等token过期了试了一下，台式上得按照你说的那样来，成功了，但是笔记本还是找不到json。昨晚太困了就睡得很早😂

**Comment by yabostone** [comment]
不行，写错了。异步不熟悉，疯狂报错。

**Comment by W4J1e** [comment]
大佬加油！
