### ISSUE TITLE
Picgo更新到2.3.1后插件无法使用

### ISSUE THREAD

**Issue by W4J1e** [W4J1e/picgo-plugin-dogecloud#10]
据PicGo的2.3.1版本 release 说明，PicGo-Core 更新到 v1.5.0 ，插件开发者请留意 ctx.request 的变化。
参考：https://picgo.github.io/PicGo-Core-Doc/zh/api/#request
由于目前被封控在学校，不放假，加之最近事情较多，暂时无法更新插件。如果有使用本插件需求的请暂勿更新 PicGo ，或者给本插件 PR 。
感谢理解。

**Comment by Pil0tXia** [comment]
期待继续更新，感谢

**Comment by W4J1e** [comment]
已更新。

**Comment by Pil0tXia** [comment]
我有一个问题，请问能指导我一下吗？我想用FileZilla管理多吉云的存储桶，不知该如何配置？
配置项如下：
![image](https://user-images.githubusercontent.com/41445332/212530661-ad1206db-c82a-46e7-af8d-157888afb7f5.png)

参考腾讯云的配置项：
![image](https://user-images.githubusercontent.com/41445332/212530737-ba0a29c0-6e83-48cc-8c93-5055973f4265.png)

参考七牛云的配置项：
![image](https://user-images.githubusercontent.com/41445332/212530893-bf12db7d-b641-40ec-bdc3-1bf247be602c.png)
“主机”打码处为存储桶名称

此外，多吉云文档中写到“外网流出流量（SDK）”是没有免费额度的，也就是说通过Filezilla下载会计费吗？
感谢！

**Comment by W4J1e** [comment]
@Pil0tXia 如果你看过多吉云的文档你就知道，由于不是用的自家的底层存储，所以相较于一般的 s3 协议来说，上传文件到多吉云的云存储需要额外携带一个 sessionToken ，而这个 token 是临时的，会过期。FileZilla 这个很显然支持一般的 s3 协议但是不能直接支持多吉云。

**Comment by Pil0tXia** [comment]
是的，客服说不发放两段式密钥了，你应该是把获取sessionToken的代码写进插件里了吧。如果想要给多吉云像其他对象存储一样做文件管理的话，你有什么想法吗？

**Comment by W4J1e** [comment]
@Pil0tXia 是的，如果想直接管理的话建议自己写个软件，软件来获取会话秘钥，但是通过 SDK 那样应该是付费的，所以看你自己哈。
