### ISSUE TITLE
SVG 上传失败，内容似乎被改变编码

### ISSUE THREAD

**Issue by zhuozhiyongde** [W4J1e/picgo-plugin-dogecloud#12]
如题。

![元数据格式](https://github.com/W4J1e/picgo-plugin-dogecloud/assets/36695271/a55bb7bf-74ab-4758-b720-7935e3e1e849)

这张 SVG 上传后会改变编码，并报错：This XML file does not appear to have any style information associated with it. The document tree is shown below.

以 wget 下载文件，vscode 打开，显示如下：

![Cleanshot-2023-12-19-at-11 52 49@2x](https://github.com/W4J1e/picgo-plugin-dogecloud/assets/36695271/e7765024-0387-4260-a1d5-2d7b203bbe33)

在 doge cloud 中点编辑也是一样的。

**Comment by zhuozhiyongde** [comment]
奇怪的是，直接在dogecloud网页中上传是正常的。

**Comment by W4J1e** [comment]
我不太明白你的意思，明天回家了我试试。

**Comment by W4J1e** [comment]
不清楚你的使用场景。
经测试，使用 `picgo-plugin-dogecloud` 上传 `SVG` 图片到多吉云存储后，在浏览器访问链接图像加载正常，curl 获取文件显示内容正常。重新编码大概率不是插件所为，请自行排查。

**Comment by zhuozhiyongde** [comment]
奇怪 我也回去尝试再复现一下

**Comment by zhuozhiyongde** [comment]
> 不清楚你的使用场景。 经测试，使用 `picgo-plugin-dogecloud` 上传 `SVG` 图片到多吉云存储后，在浏览器访问链接图像加载正常，curl 获取文件显示内容正常。重新编码大概率不是插件所为，请自行排查。

@W4J1e 我又本地测试了一下，确认上传后导致编码错误。

且与 svg 文件无关（替换为了一个图标库的标准 svg），我已确认禁用/移除所有除了 DogeCloudUpload 之外的所有插件。

我未对 DogeCloud 做任何配置上的更改。

**Comment by zhuozhiyongde** [comment]
草，更新 picgo 到 2.4.0 beta 版本后解决此问题。
