### ISSUE TITLE
picgo相册不显示图片

### ISSUE THREAD

**Issue by Elykia093** [W4J1e/picgo-plugin-dogecloud#13]
picgo相册不显示图片
![屏幕截图 2023-12-20 204623](https://github.com/W4J1e/picgo-plugin-dogecloud/assets/118417761/e44ff2e3-3c86-44f0-a86d-e4778c7d995a)

**Comment by W4J1e** [comment]
看看是不是开了防盗链，或者禁止 refer 为空，所以 picgo 无法加载
