### ISSUE TITLE
相册中无法显示缩略图的问题

### ISSUE THREAD

**Issue by kirakiseki** [W4J1e/picgo-plugin-dogecloud#9]
如图，将图片使用此插件上传之后，在PicGo的相册页面无法查看缩略图
<img width="912" alt="Pasted image 20220903202540" src="https://user-images.githubusercontent.com/38367158/188270737-91bca1a7-744d-40ec-8da5-a586c3fd3145.png">
（左侧为使用GitHub上传，右侧为使用DogeCloud上传）

点击图片后显示为禁止符号，如图
<img width="800" alt="Pasted image 20220903203346" src="https://user-images.githubusercontent.com/38367158/188270774-829dd34e-f684-4e6f-a1a4-7f59a78a76b0.png">

但可以查看到上传后图片的URL，如图
<img width="650" alt="image" src="https://user-images.githubusercontent.com/38367158/188270825-07b2784a-fb7e-43c0-bd77-daa2c9c7532f.png">

且在上传之后的消息通知里可以看到缩略图，如图
<img width="672" alt="image" src="https://user-images.githubusercontent.com/38367158/188270899-49b5d559-19cb-4e26-9d30-057b630c457a.png">

此插件的配置如下：
<img width="687" alt="image" src="https://user-images.githubusercontent.com/38367158/188270938-380b9302-812b-4cf7-aaec-48770921201d.png">

使用设备: MacBook Air M1
系统: macOS 12.4
PicGo版本: 2.3.1-beta5 （尝试过在2.3.0版本使用，问题仍然存在）

**Comment by W4J1e** [comment]
我看到你用的是控制台默认的域名，不知道默认域名官方有没有设置防盗链，禁止referer为空访问，如果有的话，就无法直接看到缩略图。我目前是用cdn加速的，在cdn里面这样配置了，同样也无法查看缩略图，点开也是禁止标识。
![image](https://user-images.githubusercontent.com/74824162/188276225-a97a5af3-2fd6-4713-9123-a59f403a729e.png)
我关掉防盗链后上传就能看到缩略图了：
![image](https://user-images.githubusercontent.com/74824162/188276303-0cc9fdee-bebe-4308-a3cd-3f36d13a81dd.png)

**Comment by kirakiseki** [comment]
感谢回复

已经找到了解决的方法：在PicGo的插件设置中，应该显式的写出`http://`或者`https://`协议，可以正常显示缩略图，而不是直接复制DogeCloud控制台中显示的域名。
<img width="489" alt="image" src="https://user-images.githubusercontent.com/38367158/188295428-90dfb180-3469-4f65-827d-9f9f9cf7b92b.png">
<img width="422" alt="image" src="https://user-images.githubusercontent.com/38367158/188295450-681ec5ac-54e4-47cb-9992-8abb4da0a51c.png">

至于防盗链的问题，似乎未绑定自定义域名，使用测试域名的情况下，并不能进行防盗链的设置。使用wget不加参数直接下载仍然能直接获取到源文件。

所以那个禁止号是DogeCloud那边返回的还是PicGo自带的占位符？

**Comment by W4J1e** [comment]
> 感谢回复
> 
> 已经找到了解决的方法：在PicGo的插件设置中，应该显式的写出`http://`或者`https://`协议，可以正常显示缩略图，而不是直接复制DogeCloud控制台中显示的域名。 <img alt="image" width="489" src="https://user-images.githubusercontent.com/38367158/188295428-90dfb180-3469-4f65-827d-9f9f9cf7b92b.png"> <img alt="image" width="422" src="https://user-images.githubusercontent.com/38367158/188295450-681ec5ac-54e4-47cb-9992-8abb4da0a51c.png">
> 
> 至于防盗链的问题，似乎未绑定自定义域名，使用测试域名的情况下，并不能进行防盗链的设置。使用wget不加参数直接下载仍然能直接获取到源文件。
> 
> 所以那个禁止号是DogeCloud那边返回的还是PicGo自带的占位符？

既然你提到了是协议的问题，那很有可能就是获取不到资源然后picgo显示的禁止符号。具体是不是可以找一个别的云存储，或者修改上传后的获取地址为一个假地址，看看有没有占位图片就知道啦。
